In [1]:
from sklearn import datasets
iris = datasets.load_iris()
print(iris.viewitems)

<built-in method viewitems of Bunch object at 0x7feb949d3868>


In [2]:
print(iris)

{'target_names': array(['setosa', 'versicolor', 'virginica'], 
      dtype='|S10'), 'data': array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.

In [3]:
sepl=iris.data[:,:1]
sepw=iris.data[:,1:2]
petl=iris.data[:,2:3]
petw=iris.data[:,3:4]
y=iris.target
print(petw)

[[ 0.2]
 [ 0.2]
 [ 0.2]
 [ 0.2]
 [ 0.2]
 [ 0.4]
 [ 0.3]
 [ 0.2]
 [ 0.2]
 [ 0.1]
 [ 0.2]
 [ 0.2]
 [ 0.1]
 [ 0.1]
 [ 0.2]
 [ 0.4]
 [ 0.4]
 [ 0.3]
 [ 0.3]
 [ 0.3]
 [ 0.2]
 [ 0.4]
 [ 0.2]
 [ 0.5]
 [ 0.2]
 [ 0.2]
 [ 0.4]
 [ 0.2]
 [ 0.2]
 [ 0.2]
 [ 0.2]
 [ 0.4]
 [ 0.1]
 [ 0.2]
 [ 0.1]
 [ 0.2]
 [ 0.2]
 [ 0.1]
 [ 0.2]
 [ 0.2]
 [ 0.3]
 [ 0.3]
 [ 0.2]
 [ 0.6]
 [ 0.4]
 [ 0.3]
 [ 0.2]
 [ 0.2]
 [ 0.2]
 [ 0.2]
 [ 1.4]
 [ 1.5]
 [ 1.5]
 [ 1.3]
 [ 1.5]
 [ 1.3]
 [ 1.6]
 [ 1. ]
 [ 1.3]
 [ 1.4]
 [ 1. ]
 [ 1.5]
 [ 1. ]
 [ 1.4]
 [ 1.3]
 [ 1.4]
 [ 1.5]
 [ 1. ]
 [ 1.5]
 [ 1.1]
 [ 1.8]
 [ 1.3]
 [ 1.5]
 [ 1.2]
 [ 1.3]
 [ 1.4]
 [ 1.4]
 [ 1.7]
 [ 1.5]
 [ 1. ]
 [ 1.1]
 [ 1. ]
 [ 1.2]
 [ 1.6]
 [ 1.5]
 [ 1.6]
 [ 1.5]
 [ 1.3]
 [ 1.3]
 [ 1.3]
 [ 1.2]
 [ 1.4]
 [ 1.2]
 [ 1. ]
 [ 1.3]
 [ 1.2]
 [ 1.3]
 [ 1.3]
 [ 1.1]
 [ 1.3]
 [ 2.5]
 [ 1.9]
 [ 2.1]
 [ 1.8]
 [ 2.2]
 [ 2.1]
 [ 1.7]
 [ 1.8]
 [ 1.8]
 [ 2.5]
 [ 2. ]
 [ 1.9]
 [ 2.1]
 [ 2. ]
 [ 2.4]
 [ 2.3]
 [ 1.8]
 [ 2.2]
 [ 2.3]
 [ 1.5]
 [ 2.3]
 [ 2. ]
 [ 2. ]
 [ 1.8]
 [ 2.1]


In [9]:
import numpy as np
seplmean=np.mean(sepl)
sepwmean=np.mean(sepw)
petlmean=np.mean(petl)
petwmean=np.mean(petw)
print(seplmean,sepwmean,petwmean,petlmean)

(5.8433333333333337, 3.0540000000000003, 1.1986666666666668, 3.7586666666666662)


In [5]:
from sklearn.neighbors import NearestNeighbors
nbrs = NearestNeighbors(n_neighbors=3, algorithm='ball_tree').fit(sepl)
distances, indices = nbrs.kneighbors(sepl)

In [6]:
print(distances,indices)

(array([[ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0.1],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0.1,  0.1],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0.1],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],


In [14]:
nbrs.kneighbors_graph(sepl).toarray()

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]])

In [7]:
seplsetosa=iris.data[0:50,:1]
seplversicolor=iris.data[50:100,:1]
seplvirginica=iris.data[100:,:1]
sepwsertosa=iris.data[:50,1:2]
sepwversicolor=iris.data[50:100,1:2]
sepwvirginica=iris.data[100:,1:2]
petlsertosa=iris.data[:50,2:3]
petlversicolor=iris.data[50:100,2:3]
petlvirginica=iris.data[100:,2:3]
petwsertosa=iris.data[:50,3:4]
petwversicolor=iris.data[50:100,3:4]
petwvirginica=iris.data[100:,3:4]

In [8]:
print(np.mean(seplsetosa))
print(np.mean(seplversicolor))
print(np.mean(seplvirginica))
print(np.mean(sepwsertosa))
print(np.mean(sepwversicolor))
print(np.mean(sepwvirginica))
print(np.mean(petlsertosa))
print(np.mean(petlversicolor))
print(np.mean(petlvirginica))
print(np.mean(petwsertosa))
print(np.mean(petwversicolor))
print(np.mean(petwvirginica))

5.006
5.936
6.588
3.418
2.77
2.974
1.464
4.26
5.552
0.244
1.326
2.026


In [5]:
import pandas as pd
misvalrep=pd.read_csv("replace.csv")

In [6]:
misval=misval

     S.No. Sepal length  Sepal width  Petal length  Petal width  \
0        1          5.1          3.5           1.4          0.2   
1        2          4.9          3.0           1.4          0.2   
2        3          4.7          3.2           1.3          0.2   
3        4          4.6          3.1           1.5          0.2   
4        5            5          3.6           1.4          0.2   
5        6          5.4          3.9           1.7          0.4   
6        7          4.6          3.4           1.4          0.3   
7        8            5          3.4           1.5          0.2   
8        9          4.4          2.9           1.4          NaN   
9       10          4.9          3.1           1.5          NaN   
10      11          5.4          3.7           1.5          0.2   
11      12          4.8          3.4           1.6          0.2   
12      13          4.8          3.0           1.4          0.1   
13      14          NaN          3.0           1.1          0.